@startuml kinokette
class Cinema {
    - List<Auditorium>
    - List<Ticket>
    - name
    - address
}

class CinemaChain {
    - List<Cinema>
    - List<Movie>
    - name
}


class Auditorium {
    - List<SeatSection>
    - List<Movie>
}

class Seat {
    - row
    - seat
}
abstract SeatSection {
    - basePrice
    - actualPrice
    - abstruct List<Seat>
}
class Row {
    - List<Seat>
}

class Loge {
    - List<Seat>
}

class Movie {
    - title
    - director
    - genre
    - productionYear
    - country
    - language
    - duration
    - rental
    - List<Actor>
}

enum Genre {
    Thriller
    Western
    YouthFilm
}

class Ticket {
    - cinema
    - auditorium
    - movieTitle
    - date
    - startTime
    - ticketCount
    - seat
    - price
}

class Actor {
    - lastname
    - firstname
    - nationality
    - birthday
    - deathday
    - notes
}

class Director {

}

SeatSection <|-- Row
SeatSection <|-- Loge
Director --|> Actor
CinemaChain "1" --> "1..*" Cinema: hat Kinos >
Cinema "1" -r-> "1..*" Auditorium: hat Säle >
SeatSection "1" -r-> "1..*" Seat: hat sitze >
Auditorium "1" --> "1..*" SeatSection: hat sitzmöglichkeiten >
Movie "1..*" <-- "1" Auditorium: spiel Filme <
Movie "1" -r-> "1..*" Actor: hat Schauspieler >
CinemaChain "1" -r-> "1..*" Movie: besitzt Filme >
Cinema "1" --> "1..*" Ticket: verkauft Tickets >
Director "1" <-- "1..*" Movie: hat Regiseur <

Genre "1" <-- "1..*" Movie: hat genre <

@enduml